Ra 03
Skip314/RecipeApp pull request #2
Opened 2024-05-13 22:49 UTC by Skip314

2024-05-14 11:29 UTC, ievetrovdev commented
Нейминги следует делать все в едином стиле (который принят в сообществе). Как правило это аббревиатура название проекта.

Например:
RA-03 create navigation buttons (для названия ПР и сообщения коммита)
RA-03-create-navigation-buttons (для названия ветки, разделение всех слов дефисами)
<img width="327" alt="Снимок экрана 2024-05-14 в 15 29 07" src="https://github.com/Skip314/RecipeApp/assets/153023186/1b820265-0a71-4164-82a5-286160dc67e9">

2024-05-14 12:08 UTC, ievetrovdev requested changes

2024-05-14 12:08 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +    android:background="#F4FAFF"
Самые часто применяемые цвета можно назвать максимально понятно по назначению, например, main_background_color

2024-05-14 12:08 UTC, ievetrovdev commented on app/build.gradle.kts
> +        viewBinding = true
В настройках подключен, но п.2 задания нужно проинициализировать в MainActivity. Смотри внимательнее ТЗ

2024-05-14 12:08 UTC, ievetrovdev commented on app/src/main/AndroidManifest.xml
> +        <meta-data
Предлагаю не использовать загружаемые шрифты, импортируй их по инструкции из урока про ресурсы.

2024-05-14 12:08 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
> +        val btnCategory: Button = findViewById(R.id.btnCategory)
Мы подключили ViewBinding, следовательно findViewById уже не нужно использовать

2024-05-14 12:08 UTC, ievetrovdev commented on app/src/main/res/drawable/shapeStyleNavButton.xml
> +<shape xmlns:android="http://schemas.android.com/apk/res/android">
На этом этапе Shape Drawable нам не понадобится. Скругленные углы задаются кнопка через стиль. Например, `<item name="cornerRadius">@dimen/main_space_half_8</item>`

2024-05-14 12:08 UTC, ievetrovdev commented on app/src/main/res/font/montserrat_alternates_medium.xml
> +<font-family xmlns:app="http://schemas.android.com/apk/res-auto"
В уроке шрифт импортируется обычным файлом .ttf

2024-05-14 12:08 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginStart="16dp"
Не обязательно для каждой стороны прописывать марджины по отдельности. Есть более универсальные атрибуты. 
android:layout_margin=""
android:layout_marginHorizontal=""
android:layout_marginVertical=""

2024-05-14 12:08 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="36dp"
Высоту контейнера для кнопок давай сделаем по размеру контента. Так как высоту предлагаю формировать через вертикальный паддинг внутри кнопки (как и прописано в ТЗ)

2024-05-14 12:08 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginStart="16dp"
Все значения размеров, цветов и т.д. выносим в ресурсы (см. ТЗ)

2024-05-14 12:08 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_width="180dp"
Внимательнее в ТЗ про кнопки расписано, значения размеров не хардкодим

2024-05-14 12:08 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            style="@style/Widget.Material3.Button.StyleNavButton"
Название верное, но пересмотри еще раз урок про стили. Создаем свой стиль StyleNavButton и отдельно указываем родителя.

2024-05-14 12:08 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        <androidx.appcompat.widget.AppCompatButton
<img width="662" alt="Снимок экрана 2024-05-14 в 15 58 12" src="https://github.com/Skip314/RecipeApp/assets/153023186/e5f2f95a-7c4a-4901-8153-f2cf2a18b561">

2024-05-14 12:08 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            tools:layout_editor_absoluteX="16dp"
Абсолютные значения позиционирования использовать не будем вообще, давай уберем. Все будет адаптивно (кроме высоты изображений, но о них позже)

2024-05-14 12:08 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            tools:ignore="MissingConstraints"
Здесь не нужно игнорировать констрейнты, так как вью не находится внутри контейнера ConstraintLayout – кнопка находится внутри контейнера с линейным позиционированием LinearLayout. В нем элементы располагаются только горизонтально или только вертикально. 

А атрибут игнорирования констрейнтов лучше вообще не использовать – корректнее проставить эти отношения там, где это будет уместно и минимум по одной привязке на каждую ось.

2024-05-14 12:08 UTC, ievetrovdev commented on app/src/main/res/values/colors.xml
> +    <color name="categori">#525DC0</color>
опечатка в названии

2024-05-14 12:08 UTC, ievetrovdev commented on app/src/main/res/values/colors.xml
> +    <color name="categori">#525DC0</color>
Вообще я за кастомные названия цветов. Причем с развернутым названием. Потому что если вдруг понадобится глобально искать по всему проекту слово category – будут проблемы в виде большого количества лишних результатов. 

Это может быть и проперти, и цвета и названия лейаутов. Поэтому для кастомных цветов предлагаю такой формат названия ресурсов, например category_color. "color" в конце обязательно для отделения одного айди ресурса от другого.

2024-05-14 12:08 UTC, ievetrovdev commented on app/src/main/res/values/preloaded_fonts.xml
> +<resources>
по шрифтам отписал. в ТЗ тоже см. пункт 5

2024-05-14 12:08 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +    <style name="AlertDialog.AppCompat.StyleTitle14">
по стилям отписал, делаем с явным родителем

2024-05-14 12:08 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">14dp</item>
Размер шрифтов указывается в Scalable pixels (sp), все остальные размеры указываются в Density-independent pixels (dp). Рекомендую пересмотреть уроки по ресурсам.

2024-05-17 10:28 UTC, ievetrovdev commented
коммит мессаджи лучше делать чуть более осмысленными

<img width="205" alt="Снимок экрана 2024-05-17 в 14 28 14" src="https://github.com/Skip314/RecipeApp/assets/153023186/9eed9cf5-26b8-4f8d-bc92-73a35b081419">

2024-05-17 10:34 UTC, ievetrovdev requested changes

2024-05-17 10:34 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
>          ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main)) { v, insets ->
Этот код из новых версий Android Studio можно оставить. Он используется для корректной обработки window insets элементы типа статус-бара или нав-бара.

2024-05-17 10:34 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="36dp"
не исправлено

2024-05-17 10:34 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginStart="16dp"
не исправлено (все остальные комменты ниже тоже)

2024-05-17 10:34 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginBottom="55dp"
Считаем нижней гранью экрана на макете нарисованный навбар. До него расстояние 8dp

2024-05-23 05:52 UTC, ievetrovdev requested changes

2024-05-23 05:52 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="36dp"
Снова не исправлено

2024-05-23 05:52 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            android:text="uзбpahhoe"
тексты тоже выносим в ресурсы strings.xml

2024-05-23 05:52 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="main_layout_btn_gap">8dp</dimen>
Повторять одни и те же значения размеров с разными айдишниками не рекомендуется. Пусть в dimens хранятся только уникальные айтемы, а уникализировать значения для разных элементов интерфейса корректнее через кастомные стили.

2024-05-23 05:52 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="main_layout_btn_gap">8dp</dimen>
Стиль названия ресурсов в приложении обычно скорее придумывается, чем берется како-либо эталонный стиль. Существуют разные подходы.

Можно в названии писать цифру в конце, которая означает размер, а можно использовать такую структуру, например

<img width="687" alt="Снимок экрана 2024-05-23 в 09 48 18" src="https://github.com/Skip314/RecipeApp/assets/153023186/4d4449e3-d8d2-4f19-b979-ffaeb42e941c">

2024-05-23 05:52 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_marginEnd="@dimen/main_layout_btn_gap"
Расстояние по макету между кнопками 4dp. Причем, чтобы их не перекашивало лучше добавлять по 2 пиксела с каждой стороны

2024-05-23 05:52 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="fontFamily">@font/montserrat_alternates_medium</item>
Кнопки в макете представлены полужирным шрифтом montserrat_alternates_semi_bold

2024-05-23 05:52 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:paddingVertical">1dp</item>
кажется тут нужное значение 10dp

2024-05-24 09:47 UTC, ievetrov approved these changes

2024-05-28 12:06 UTC, merged