RA 05 create favorite fragment
Skip314/RecipeApp pull request #4
Opened 2024-05-30 11:12 UTC by Skip314

2024-05-30 17:26 UTC, ievetrovdev requested changes

2024-05-30 17:26 UTC, ievetrovdev commented on app/src/main/AndroidManifest.xml
> +        <activity
1. FavoritesFragment это не активити
2. Фрагменты не нужно регистрировать в манифесте

2024-05-30 17:26 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
>          with(binding) {
Не используешь объединение для элементов ниже

2024-05-30 17:26 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
>          supportFragmentManager.commit {
Для второй кнопки тоже нужен слушатель кликов. кнопка с категориями не нажимается (не забывай тестировать приложение перед отправкой ПР, чтобы все работало согласно ТЗ)

2024-06-05 17:38 UTC, ievetrov requested changes

2024-06-05 17:38 UTC, ievetrov commented on app/src/main/assets/burger.png
не вижу чтобы в этом тз было требование добавлять картинки

2024-06-05 17:38 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/Category.kt
> +class Category(
и сущности

2024-06-05 17:38 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
>          supportFragmentManager.commit {
ничего не исправлено

2024-06-05 17:38 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/Recipes.kt
> +class Recipes {
это что такое?

2024-06-05 18:22 UTC, Skip314 commented on app/src/main/java/com/example/recipeapp/Recipes.kt
> +class Recipes {
что тут надо исправить?
это почему то бранчи клонировались

2024-06-06 09:51 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/Recipes.kt
> +class Recipes {
это просто ненужный код (и файл) в рамках этого ПР

2024-06-06 09:51 UTC, ievetrov approved these changes

2024-06-06 13:43 UTC, merged